[package]
name = "metasupply_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.1" # Compatible with ic-cdk 0.12.0
ic-cdk = "0.12.0"
ic-cdk-macros = "0.8.0"
serde = "1.0.197"